### ISSUE TITLE
model.save('my_first.h5')  error when running model

### ISSUE THREAD

**Issue by velociwabbit** [transcranial/keras-js#104]
I have taken the liberty of adding the save statement to the supplied mnist_cnn.py example found in the repo (see code below)... Although the save option worked  and the next step also worked which was

**>python encoder.py --name .\my_first.h5 .\my_first.h5**

when i went to test the results in a javascript app i encountered this result:

`Uncaught (in promise) Error: [Model] Model configuration does not contain any layers.
    at t (http://localhost:3003/keras.min.js:1:414319)
    at t (http://localhost:3003/keras.min.js:1:411416)
    at r (http://localhost:3003/keras.min.js:1:448353)
    at Generator.i [as _invoke] (http://localhost:3003/keras.min.js:1:449400)
    at Generator.t.(anonymous function) [as throw] (http://localhost:3003/keras.min.js:1:448532)
    at i (http://localhost:3003/keras.min.js:1:164739)
    at s (http://localhost:3003/keras.min.js:1:164860)
    at <anonymous>
2keras.min.js:1 Uncaught (in promise) Error: [Model] predict() must take an object where the keys are the named inputs of the model: []
    at t (http://localhost:3003/keras.min.js:1:419002)
    at r (http://localhost:3003/keras.min.js:1:448353)
    at Generator.i [as _invoke] (http://localhost:3003/keras.min.js:1:449400)
    at Generator.t.(anonymous function) [as next] (http://localhost:3003/keras.min.js:1:448532)
    at i (http://localhost:3003/keras.min.js:1:164739)
    at a (http://localhost:3003/keras.min.js:1:164834)
    at http://localhost:3003/keras.min.js:1:164892
    at new Promise (<anonymous>)
    at t.<anonymous> (http://localhost:3003/keras.min.js:1:164683)
    at t.e (http://localhost:3003/keras.min.js:1:420220)
    at mouseUpLeave (http://localhost:3003/kerdex.html:63:60)
    at HTMLCanvasElement.digcanvas.onmouseup.e (http://localhost:3003/kerdex.html:69:49)`

No doubt i have done something silly but   I am unsure what it is... I am just trying to confirm that. i can build a bin file that works so that i can implement my own model/app.

the full text of mnist_cnn.py with the extra line **model.save('my_first.h5') i**s included below:

Thanks  

 ```

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
 
batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(  x_test.shape[0] , 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train  = x_train.astype('float32')
x_test   = x_test.astype('float32')
x_train /= 255
x_test  /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model   = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu',  input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,  optimizer=keras.optimizers.Adadelta(),  metrics=['accuracy'])

model.fit(x_train, y_train,  batch_size=batch_size,  epochs=epochs,   verbose=1, validation_data=(x_test, y_test))

model.save('my_first.h5')

 score = model.evaluate(x_test, y_test, verbose=0) 
 
print('Test loss:', score[0])
print('Test accuracy:', score[1])
 
```

**Comment by blakewintermute** [comment]
I have not gotten everything to work yet, but I will say that right now you need to train on keras v2.0.9  Other versions create the 'no layers' error. Good luck with the rest!

**Comment by hmhwe** [comment]
Did you find a solution for the error?

**Comment by blakewintermute** [comment]
If I'm honest, I don't remember if I did.

**Comment by blakewintermute** [comment]
I do remember making a basic model and bearly training it on every different version of keras until it would be accepted by keras.js, but I don't remember which worked or anything beyond that. I believe the makers of keras changed how they structured the model files a few times throughout development.
