### ISSUE TITLE
Convolution1D error with input (None,1)

### ISSUE THREAD

**Issue by wassname** [transcranial/keras-js#22]
I noticed an error building Convolutional1D layer in js when the input has 1 feature layer. I added a failing test for it to [this fork](https://github.com/wassname/keras-js), so that it can be easily reproduced.

Here is the error reported at localhost:3000/test (all other tests pass)
```
Error: cwise: Arrays do not all have the same shape!
    at assign_cwise_thunk (eval at createThunk (eval at <anonymous> (http://localhost:3000/dist/keras.js:2858:1)), <anonymous>:8:71)
    at Object.assign_ndarrayops [as assign] (eval at makeOp (eval at <anonymous> (http://localhost:3000/dist/keras.js:108:1)), <anonymous>:3:43)
    at Convolution2D._w2row (eval at <anonymous> (http://localhost:3000/dist/keras.js:493:1), <anonymous>:274:30)
    at Convolution2D.setWeights (eval at <anonymous> (http://localhost:3000/dist/keras.js:493:1), <anonymous>:126:12)
    at Convolution1D.setWeights (eval at <anonymous> (http://localhost:3000/dist/keras.js:1355:1), <anonymous>:103:20)
    at r.<anonymous> (convolutional/Convolution1D.js:61:19)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12791)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:12855
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:559)
```

**Comment by wassname** [comment]
Sorry, I've looked a bit further and it seems to be a problem with my Keras. It givesweights with permuted dimensions. E.g. for the Convolution1d notebook, on the first test cell I get `W shape: (3, 1, 2, 4)` instead of `W shape: (4, 2, 3, 1)`. Could someone tell me which version of keras is used for testing?

**Comment by wassname** [comment]
Closing because this is likely due to an old version of tensorflow

**Comment by wassname** [comment]
Upgraded tensorflow to `0.11.0rc2` and my weights are still permuted. If anyone has any ideas I would appreciate it.

**Comment by stekaiser** [comment]
I think I am experiencing the same error. Were you able to resolve it?

**Comment by wassname** [comment]
No I worked around it by modifying the permuted weights or avoiding that layer. I think it would be a good idea to modify the tests  to include data export, that way we would have coverage of issues like this.

**Comment by stekaiser** [comment]
I dug a bit deeper and it is possibly due to a change in Keras.

On Sep 14 Keras changed the `dim_ordering` in `Convolution1D` to `tf`(see [here](https://github.com/fchollet/keras/commit/9f6acd960c0a0c699c79ca1d571783e1692568fb#diff-d462a3275abee3aa77ba2b341e45cf20R158)). However, the corresponding code in Keras.js was not touched since August 27 (see [here](https://github.com/transcranial/keras-js/commit/ef6f18bd0a64ca51b86152fa4d917f80bcc95265#diff-dbbf3f49a9d8216fd821a2fe0b07eff7R40)).

I will see if I can fix this and create a pull request.

**Comment by wassname** [comment]
Oh nice, it's good to see the reason.
