### ISSUE TITLE
Error building for Ubuntu 16.04

### ISSUE THREAD

**Issue by LRonHubs** [transcranial/keras-js#23]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle keras-js@0.1.0~prewatch: keras-js@0.1.0
6 silly lifecycle keras-js@0.1.0~prewatch: no script for prewatch, continuing
7 info lifecycle keras-js@0.1.0~watch: keras-js@0.1.0
8 verbose lifecycle keras-js@0.1.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle keras-js@0.1.0~watch: PATH: /usr/share/npm/bin/node-gyp-bin:/home/y/crypto/keras-js/node_modules/.bin:/home/y/bin:/home/y/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle keras-js@0.1.0~watch: CWD: /home/y/crypto/keras-js
11 silly lifecycle keras-js@0.1.0~watch: Args: [ '-c', 'webpack --watch --config webpack.dev.config.js' ]
12 info lifecycle keras-js@0.1.0~watch: Failed to exec watch script
13 verbose stack Error: keras-js@0.1.0 watch: `webpack --watch --config webpack.dev.config.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid keras-js@0.1.0
15 verbose cwd /home/y/crypto/keras-js
16 error Linux 4.4.0-45-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error keras-js@0.1.0 watch: `webpack --watch --config webpack.dev.config.js`
24 error spawn ENOENT
25 error Failed at the keras-js@0.1.0 watch script 'webpack --watch --config webpack.dev.config.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the keras-js package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     webpack --watch --config webpack.dev.config.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs keras-js
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls keras-js
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```
When installing:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN keras-js@0.1.0 scripts['server'] should probably be scripts['start'].
```

**Comment by LRonHubs** [comment]
Error is slightly different after running these comands:
npm install webpack; npm install lint; 


> Failed at the keras-js@0.1.0 build script 'npm run lint && webpack --config webpack.prod.config.js'.

**Comment by LRonHubs** [comment]
Install webpack globally instead:
`npm install webpack -g`
Then, create a symbolic link from "nodejs" to "node" if you haven't already
```
sudo apt-get install nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node
```
