### ISSUE TITLE
ConvVAE is not working

### ISSUE THREAD

**Issue by gokceneraslan** [transcranial/keras-js#4]
Thanks for the great project! I get the following error with Chrome 54.0.2840.59 when I click on a point in the latent space.

![image](https://cloud.githubusercontent.com/assets/1140359/19380852/4da59a5e-91f9-11e6-835d-5c871922e235.png)

**Comment by gokceneraslan** [comment]
It's this line:

```js
console.warn("%c" + t, e ? "color: darkorange" : "color: red")
```

**Comment by transcranial** [comment]
@gokceneraslan it's just the conv VAE? what OS are you on? I can't reproduce on ubuntu or mac osx, with that exact chrome version.

**Comment by gokceneraslan** [comment]
Basic MNIST works fine. I'm on Arch Linux. `e` is undefined here:

![image](https://cloud.githubusercontent.com/assets/1140359/19408535/e67b5e0a-92bf-11e6-9c35-db15b3cf4e30.png)

and `this.output` is undefined here:

![image](https://cloud.githubusercontent.com/assets/1140359/19408527/cfad7ef6-92bf-11e6-95a9-64a71ff4fa81.png)

**Comment by albanm** [comment]
Same problem here. The stack is similar but at other lines: 

```
bluebird.js?e366:1546 Unhandled rejection TypeError: Cannot read property '0' of undefined
    at Object.d [as image2Darray] (https://transcranial.github.io/keras-js/demos/dist/bundle.js:1:8037)
    at VueComponent.drawOutput (https://transcranial.github.io/keras-js/demos/dist/bundle.js:4:2527)
    at VueComponent.drawOutput (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js:6:1328)
    at https://transcranial.github.io/keras-js/demos/dist/bundle.js:4:2394
From previous event:
    at VueComponent.runModel (https://transcranial.github.io/keras-js/demos/dist/bundle.js:4:2348)
    at VueComponent.runModel (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js:6:1328)
    at VueComponent.<anonymous> (https://transcranial.github.io/keras-js/demos/dist/bundle.js:4:925)
    at Array.o (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js:7:9721)
    at MutationObserver.t (https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js:7:9400)
```

Recent chrome on ubuntu and other demos are ok.
