### ISSUE TITLE
[Model] Error loading weights

### ISSUE THREAD

**Issue by anandanand84** [transcranial/keras-js#60]
Error loading weights without much information even though the network shows 200 for all the files. Below is the stacktrace.
Error: [Model] error loading weights.
    at http://localhost:5444/node_modules/keras-js/dist/keras.js:4:18404
    at Array.map (native)
    at http://localhost:5444/node_modules/keras-js/dist/keras.js:4:18250
    at Array.forEach (native)
    at t.value (http://localhost:5444/node_modules/keras-js/dist/keras.js:4:16687)
    at http://localhost:5444/node_modules/keras-js/dist/keras.js:4:15092
From previous event:
    at t.value (http://localhost:5444/node_modules/keras-js/dist/keras.js:4:15067)
    at new t (http://localhost:5444/node_modules/keras-js/dist/keras.js:4:14730)
    at Object.38 (http://localhost:5444/dist/browser.js:79:877)
    at s (http://localhost:5444/dist/browser.js:1:254)
    at http://localhost:5444/dist/browser.js:1:305
    at Object.41../Utils/AverageGain (http://localhost:5444/dist/browser.js:85:1110)
    at s (http://localhost:5444/dist/browser.js:1:254)
    at http://localhost:5444/dist/browser.js:1:305
    at Object.<anonymous> (http://localhost:5444/dist/browser.js:5:29)
    at Object.2../lib (http://localhost:5444/dist/browser.js:6:4)
    at s (http://localhost:5444/dist/browser.js:1:254)
    at http://localhost:5444/dist/browser.js:1:305
    at Object.1../index.js (http://localhost:5444/dist/browser.js:2:14)
    at s (http://localhost:5444/dist/browser.js:1:254)
    at e (http://localhost:5444/dist/browser.js:1:425)
    at http://localhost:5444/dist/browser.js:1:443

![print](https://cloud.githubusercontent.com/assets/5538452/25074753/9f5d7ab4-22c8-11e7-8d89-fc85a89839e0.png)

**Comment by dribnet** [comment]
Are you using weights from a model you trained yourself, or sample weights included with the repo? If your own model, was it run with Keras 1.1.0? I believe that is the only version of Keras this repo currently supports.

**Comment by anandanand84** [comment]
I am using weights from the model I trained, and  the version of keras is 2.0.3. So is that the issue?

**Comment by dribnet** [comment]
[yes](https://github.com/transcranial/keras-js/issues/49#issuecomment-290943452). perhaps we should probably open a top-level issue for this for visibility/tracking.
