### ISSUE TITLE
"TypeError: expecting a function but got [object Undefined]" occurs when I read the model

### ISSUE THREAD

**Issue by LittleWat** [transcranial/keras-js#63]
Hello. Thanks for a nice implementation!

I am new to Javascript and I would like you to explain how to use this library in detail.

I installed the keras-js using npm and I tried to check if the model created in Keras(Python) can be loaded correctly. But it didn't work.

Here is my log.

```
➜  simple-keras-js node
> const KerasJS = require('keras-js');
undefined
>
> var model = new KerasJS.Model({
...     filepaths: {
.....         model: './data/mnist_cnn.json',
.....         weights: './data/mnist_cnn_weights.buf',
.....         metadata: './data/mnist_cnn_metadata.json'
.....     },
...     filesystem: true
... });
TypeError: expecting a function but got [object Undefined]
    at Function.e.promisify (/Users/kwatanabe/node_modules/keras-js/dist/keras.js:1:391803)
    at t.value (/Users/kwatanabe/node_modules/keras-js/dist/keras.js:1:111338)
    at /Users/kwatanabe/node_modules/keras-js/dist/keras.js:1:111107
    at Array.map (native)
    at t.value (/Users/kwatanabe/node_modules/keras-js/dist/keras.js:1:111069)
    at new t (/Users/kwatanabe/node_modules/keras-js/dist/keras.js:1:110823)
    at repl:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:241:10)
    at REPLServer.Interface._line (readline.js:590:8)
>
(To exit, press ^C again or type .exit)
> %
```

**Comment by LittleWat** [comment]
I could use! This error happened maybe because my npm setting was wrong.

Thanks anyway!
