### ISSUE TITLE
Unable to generate model_weights.buf and model_metadata.json 

### ISSUE THREAD

**Issue by ghassanmas** [transcranial/keras-js#87]
I got error when running: 

`$ python encoder.py /path/to/model.hdf5`

Which is : 

`Traceback (most recent call last):
  File "encoder.py", line 114, in <module>
    encoder.serialize()
  File "encoder.py", line 62, in serialize
    self.model.model_config = hdf5_file.attrs['model_config']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ghassan/anaconda2/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (Can't locate attribute: 'model_config')"
`
The way I generated the model.hdf5 file is by : 
`happyModel.save_weights("model.hdf5"`

Using Keras version: 2.0.7

**Comment by kvue** [comment]
I am really new to all this and I was also getting  the same error. Then I found this closed issue link: https://github.com/transcranial/keras-js/issues/86  

I was able to run encoder by saving the whole model instead of just the weights:  model.save("model.h5"). I got a .bin file instead of model_weights.buf and model_metadata.json. 
When I try to load it in a script tag in my index.html, I get: 

Uncaught Error: File paths must be declared for model, weights, and metadata.
    at new t (keras.js:7)
    at king.html:11

So I am stuck on what to do with this bin file. My question would be if I need to use node.js, which would be new to me.

**Comment by kvue** [comment]
I'm having the same issue using latest version of Kereas. After digging around the closed issues I was able to use encoder.py and got a .bin. I do not now what to do with it now cause I just want to load it inside my html file but keras still requires the three separate files.

**Comment by ghassanmas** [comment]
I did the same by saving the whole model as hdf5 file I was able to generate the .bin using the encoder.py but then when trying to load the model in keras.js it expect 3 files !. 
I am also using keras.js as a file, I don't think it would make such a different using node.js only if the module in node,js is updated such that when creating a new model it could take the file .bin as the only argument.

**Comment by kvue** [comment]
Okay, I was able to get the generate model_weights.buf and model_metadata.json using the earlier version of keras.js, v0.1.0. Maybe try that? After using keras.js as a file, open it with firefox, using chrome gives errors. I didn't get any errors this way but I got a blank screen. I don't know if the model load correctly.

**Comment by kvue** [comment]
The encoder from the keras.js v3 release page:https://github.com/transcranial/keras-js/releases
 gives you the model_weights.buf and model_metadata.json files.

**Comment by jageshmaharjan** [comment]
@kvue , keras.js v3, worked for me.
Thanks

**Comment by ghassanmas** [comment]
@kvue Also worked for me ! much appreciated. 
You know also when downloading the project from https://github.com/transcranial/keras-js/releases the hierarchy of files is different for example the "encoder.py" is in the root.

**Comment by fedden** [comment]
The releases encoder.py file also works for me! Thanks

**Comment by EzzatOmar** [comment]
Thanks for pointing to the right solution!!

**Comment by YacineBenzerga** [comment]
@kvue Gratitude the help..much appreciated
